spring.application.name=MiniProjectSS13

logging.level.root=INFO
logging.level.rikkei.edu.miniprojectss13.controller=DEBUG
logging.level.rikkei.edu.miniprojectss13.service=DEBUG
logging.pattern.console=%d{HH:mm:ss} [%level] %logger{36} - %msg%n
